# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-metric-samples

replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/qm-ace-sit/mq-metric-prometheus
  tag: 5.5.4
  pullPolicy: IfNotPresent
  port: 9157

service:
  type: ClusterIP
  port: 9157

route:
  enabled: true

ingress:
  enabled: false

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: QM

configmap:
  QM: "QM1"
  CONNECTION_NAME: "qm01-qm-ibm-mq.qm-ace-sit.svc.cluster.local(1414)"
  CHANNEL: "MONITORING_CHL"
  QUEUES: "!SYSTEM.*,!AMQ.*,*"
  SUBSCRIPTIONS: "!$SYS*"
  TOPICS: "!*"
  USE_PUBLICATIONS: false
  USE_OBJECT_STATUS: true
  CONFIGURATION_FILE: ""
  LOG_LEVEL: "INFO"
